### ISSUE TITLE
Converter from radio to laser has a delay

### ISSUE THREAD

**Issue by lmandres** [lmandres/GGJTeamPSU2018#4]
# Description
Converter from radio to laser has a delay

# Steps to Reproduce
1. Build Space Bubbles to executable
2. Double-click on executable
3. Select settings and click "Play!"
4. Click "New Game" button
5. In game, place a radio/laser convertor that receives and triggers the convertor

# Expected Functionality
The laser should detect the collision immediately

# Actual Functionality
There is a delay between detection of the collision and conversion of the laser.

**Comment by lmandres** [comment]
This might be by game design, but it is not expected, and for a moment, it seems like it was a fail for the level.

**Comment by Klezst** [comment]
At the time this bug was reported, the animations were broken. However the delays that wait for the animation to run were still in place. Now that the animations are back it may make sense. Alternatively, the sprite or collision box may be in the wrong place on the splitter. Try resetting the coordinates for the sprite to 0, 0, 0 to see if that helps. If not, verify the location of the collider.

**Comment by lmandres** [comment]
The animations now work, and the delay makes sense.
